image:
  - Visual Studio 2019
  
install:  
  - git submodule update --init --recursive
  
before_build:
- cmd: cmake -H.\glm -G "Visual Studio 16 2019" -A Win32 -B./build_x86 -DCMAKE_INSTALL_PREFIX=./package_x86 -DGLM_TEST_ENABLE="OFF"
- cmd: cmake -H.\glm -G "Visual Studio 16 2019" -A x64 -B./build_x64 -DCMAKE_INSTALL_PREFIX=./package_x64 -DGLM_TEST_ENABLE="OFF"
    
build_script:
- cmd: cmake --build build_x86 --target ALL_BUILD --config Release
- cmd: cmake --build build_x64 --target ALL_BUILD --config Release
  
after_test:
  - cmd: nuget pack -Version %APPVEYOR_BUILD_VERSION%
  
artifacts:
  - path: '**\*.nupkg'
  
deploy:
- provider: Environment
  name: production